export const DATA_FETCH_INITIATED = 'DATA_FETCH_INITIATED';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';
export const HANDLER_CLICKED = 'HANDLER_CLICKED';
export const SEARCH_QUERY = 'SEARCH_QUERY';
